site:
  name: Shemirat Enayim
  site: 'https://shemiratenayim.org'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null # Will be configured during deployment

# Default SEO metadata
metadata:
  title:
    default: 'Shemirat Enayim - Protection for the Eyes'
    template: '%s — Shemirat Enayim'
  description: "Comprehensive resources for parents, religious leaders, and individuals to protect their networks from inappropriate content through content filtering and internet safety solutions."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Shemirat Enayim'
    images:
      - url: '~/assets/images/og-image.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@shemiratenayim'
    site: '@shemiratenayim'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false  # Disabled - this is a resource site, not a blog
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null # Not using Google Analytics
    plausible:
      domain: 'shemiratenayim.org'  # Plausible Analytics for privacy-respecting tracking
    # Sentry will be configured in astro.config.ts

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

# Shemirat Enayim specific configuration
shemiratenayim:
  audiences:
    - parents
    - organizations
    - individuals
  features:
    search: true
    newsletter: true
    forms:
      contact: true
      feedback: true
